const nodemailer = require('nodemailer');

// ─────────────────────────────────────────────────────────────────────────────
//  Sandigan Email Service
//  Handles all outbound transactional emails to customers.
//  All send functions are fire-and-forget — errors are logged but never thrown.
// ─────────────────────────────────────────────────────────────────────────────

const transporter = nodemailer.createTransport({
    service: 'gmail',
    auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
    },
});

// ─── Shared Helpers ──────────────────────────────────────────────────────────

/**
 * Format a number as Philippine Peso (₱1,500.00)
 */
const formatPeso = (amount) =>
    `₱${Number(amount || 0).toLocaleString('en-PH', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;

/**
 * Format a Date to a readable string in Manila timezone
 */
const formatDate = (date) => {
    if (!date) return '—';
    return new Date(date).toLocaleDateString('en-PH', {
        timeZone: 'Asia/Manila',
        year: 'numeric',
        month: 'long',
        day: 'numeric',
    });
};

/**
 * Format a datetime string (e.g., "2026-07-29T10:00") to readable form
 */
const formatBookingTime = (bookingTime) => {
    if (!bookingTime) return '—';
    try {
        const d = new Date(bookingTime);
        if (isNaN(d.getTime())) return bookingTime; // Return raw if not parseable
        return d.toLocaleString('en-PH', {
            timeZone: 'Asia/Manila',
            year: 'numeric',
            month: 'long',
            day: 'numeric',
            hour: '2-digit',
            minute: '2-digit',
            hour12: true,
        });
    } catch {
        return bookingTime;
    }
};

// ─── Shared Email Wrapper ────────────────────────────────────────────────────

const wrapInShell = (content, preheader = '') => `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Sandigan Car Services</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { background-color: #0f0f13; font-family: 'Segoe UI', Arial, sans-serif; color: #e2e8f0; }
    a { color: #6366f1; text-decoration: none; }
    @media only screen and (max-width: 600px) {
      .container { width: 100% !important; border-radius: 0 !important; }
      .details-table td { display: block; width: 100% !important; }
      .details-table .label { padding-bottom: 2px; }
    }
  </style>
</head>
<body>
  <!-- Preheader text (invisible, shown in inbox preview) -->
  <span style="display:none;font-size:1px;color:#0f0f13;max-height:0;max-width:0;opacity:0;overflow:hidden;">${preheader}</span>

  <table width="100%" cellpadding="0" cellspacing="0" style="background:#0f0f13; padding: 32px 16px;">
    <tr>
      <td align="center">
        <table class="container" width="600" cellpadding="0" cellspacing="0"
          style="background:#1a1a24; border-radius:16px; overflow:hidden; border:1px solid #2d2d3f;">

          <!-- ── Header ── -->
          <tr>
            <td style="background: linear-gradient(135deg, #1e1e30 0%, #252535 100%);
                        padding: 36px 40px; text-align: center;
                        border-bottom: 1px solid #2d2d3f;">
              <div style="display:inline-block; background: linear-gradient(135deg, #6366f1, #8b5cf6);
                          border-radius: 12px; padding: 10px 20px; margin-bottom: 16px;">
                <span style="font-size: 22px; font-weight: 800; color: #fff; letter-spacing: 1px;">🚗 SANDIGAN</span>
              </div>
              <div style="font-size: 13px; color: #94a3b8; letter-spacing: 2px; text-transform: uppercase;">
                Car Wash &amp; Car Rental Services
              </div>
            </td>
          </tr>

          <!-- ── Body Content ── -->
          <tr>
            <td style="padding: 36px 40px;">
              ${content}
            </td>
          </tr>

          <!-- ── Footer ── -->
          <tr>
            <td style="background: #13131c; padding: 24px 40px; border-top: 1px solid #2d2d3f; text-align: center;">
              <div style="display:inline-block; background:#1e1e30; border:1px solid #2d2d3f;
                  border-radius:99px; padding:5px 16px; margin-bottom:14px;">
                <span style="font-size:11px; color:#6366f1; font-weight:600; letter-spacing:1px; text-transform:uppercase;">
                  🤖 This is an autogenerated email
                </span>
              </div>
              <p style="font-size: 12px; color: #64748b; line-height: 1.6;">
                This email was automatically sent upon booking submission. Please do not reply.<br/>
                For inquiries, contact us directly through our website or in-store.<br/><br/>
                <span style="color: #475569;">© ${new Date().getFullYear()} Sandigan Car Services. All rights reserved.</span>
              </p>
            </td>
          </tr>

        </table>
      </td>
    </tr>
  </table>
</body>
</html>
`;

// ─── Row Helper ─────────────────────────────────────────────────────────────

const row = (label, value) => `
<tr>
  <td class="label" style="padding: 10px 16px; font-size: 13px; color: #94a3b8;
      font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px;
      width: 40%; border-bottom: 1px solid #252535; vertical-align: top;">
    ${label}
  </td>
  <td style="padding: 10px 16px; font-size: 14px; color: #e2e8f0;
      border-bottom: 1px solid #252535; vertical-align: top;">
    ${value || '—'}
  </td>
</tr>`;

// ─── Receipt ID Badge ────────────────────────────────────────────────────────

const receiptBadge = (id, label = 'Receipt / Reference ID') => `
<div style="background: linear-gradient(135deg, #1e1b4b, #1e2040);
            border: 2px dashed #6366f1; border-radius: 12px;
            padding: 20px 24px; margin: 24px 0; text-align: center;">
  <div style="font-size: 12px; color: #818cf8; text-transform: uppercase;
              letter-spacing: 2px; font-weight: 600; margin-bottom: 8px;">
    ${label}
  </div>
  <div style="font-size: 28px; font-weight: 800; color: #a5b4fc;
              letter-spacing: 4px; font-family: 'Courier New', monospace;">
    ${id}
  </div>
  <div style="font-size: 11px; color: #64748b; margin-top: 8px;">
    Please save this ID — you may use it when following up with us.
  </div>
</div>`;

// ─── Status Badge ────────────────────────────────────────────────────────────

const statusBadge = (status) => {
    const colors = {
        Pending:   { bg: '#1c1a0d', border: '#d97706', text: '#fbbf24' },
        Confirmed: { bg: '#0d1c14', border: '#16a34a', text: '#4ade80' },
        Cancelled: { bg: '#1c0d0d', border: '#dc2626', text: '#f87171' },
    };
    const c = colors[status] || colors.Pending;
    return `<span style="display:inline-block; background:${c.bg}; border:1px solid ${c.border};
        color:${c.text}; font-size:12px; font-weight:700; padding:4px 14px;
        border-radius:99px; letter-spacing:1px; text-transform:uppercase;">${status}</span>`;
};

// ─────────────────────────────────────────────────────────────────────────────
//  1. Car Wash Booking Confirmation
// ─────────────────────────────────────────────────────────────────────────────

const sendBookingConfirmation = async (booking) => {
    if (!booking?.emailAddress) return;

    const customerName = `${booking.firstName} ${booking.lastName}`;
    const services = Array.isArray(booking.serviceType)
        ? booking.serviceType.join(', ')
        : (booking.serviceType || '—');

    // Build discount rows if applicable
    let discountRows = '';
    if (booking.promoCode || booking.discountAmount > 0) {
        if (booking.promoCode) {
            discountRows += row('Promo Code', `<code style="background:#1e2040;padding:2px 8px;border-radius:4px;color:#a5b4fc;">${booking.promoCode}</code>`);
        }
        if (booking.promoDiscount > 0) {
            discountRows += row('Promo Discount', `<span style="color:#4ade80;">-${formatPeso(booking.promoDiscount)}</span>`);
        }
        if (booking.discountAmount > 0) {
            discountRows += row('Other Discount', `<span style="color:#4ade80;">-${formatPeso(booking.discountAmount)}</span>`);
        }
    }

    // Purchased products
    let productRows = '';
    if (Array.isArray(booking.purchasedProducts) && booking.purchasedProducts.length > 0) {
        const productList = booking.purchasedProducts
            .map(p => `${p.productName} x${p.quantity} (${formatPeso(p.price)})`)
            .join('<br/>');
        productRows = row('Add-on Products', productList);
    }

    // Home service address
    let locationRow = '';
    if (booking.serviceLocationType === 'Home Service' && booking.homeServiceDetails?.address) {
        locationRow = row('Home Service Address', booking.homeServiceDetails.address);
    }

    const content = `
      <!-- Greeting -->
      <h2 style="font-size: 22px; font-weight: 700; color: #f1f5f9; margin-bottom: 6px;">
        Booking Confirmed! 🎉
      </h2>
      <p style="font-size: 14px; color: #94a3b8; margin-bottom: 4px;">
        Hi <strong style="color:#e2e8f0;">${customerName}</strong>, thank you for booking with Sandigan!
      </p>
      <p style="font-size: 14px; color: #94a3b8; margin-bottom: 24px;">
        Your car wash booking has been received and is currently <strong style="color:#fbbf24;">pending confirmation</strong>.
        We'll take care of your vehicle!
      </p>

      ${receiptBadge(booking.batchId, 'Booking Reference ID')}

      <!-- Details Table -->
      <table class="details-table" width="100%" cellpadding="0" cellspacing="0"
        style="border-radius:10px; overflow:hidden; border:1px solid #2d2d3f; margin-bottom: 24px;">
        ${row('Status', statusBadge('Pending'))}
        ${row('Customer Name', customerName)}
        ${row('Phone Number', booking.phoneNumber || '—')}
        ${row('Vehicle Type', booking.vehicleType || '—')}
        ${row('Service(s)', services)}
        ${row('Preferred Date & Time', formatBookingTime(booking.bookingTime))}
        ${row('Service Type', booking.serviceLocationType || 'In-Store')}
        ${locationRow}
        ${productRows}
        ${discountRows}
        ${row('Total Amount', `<strong style="font-size:16px;color:#a5b4fc;">${formatPeso(booking.totalPrice)}</strong>`)}
      </table>

      <p style="font-size: 13px; color: #64748b; line-height: 1.7; background:#13131c;
          border-left: 3px solid #6366f1; padding: 12px 16px; border-radius: 0 8px 8px 0;">
        ℹ️ Your booking is <strong style="color:#fbbf24;">pending</strong> — our team will review it and confirm your slot shortly.
        You may reach out to us if you need to make any changes.
      </p>
    `;

    const html = wrapInShell(content,
        `Your booking ${booking.batchId} has been received. Thank you, ${booking.firstName}!`
    );

    try {
        await transporter.sendMail({
            from: process.env.EMAIL_FROM,
            to: booking.emailAddress,
            subject: `Booking Confirmed — ${booking.batchId} | Sandigan Car Wash`,
            html,
        });
        console.log(`✅ [Email] Booking confirmation sent to ${booking.emailAddress} (${booking.batchId})`);
    } catch (err) {
        console.error(`❌ [Email] Failed to send booking confirmation to ${booking.emailAddress}:`, err.message);
        // Non-critical — do NOT re-throw
    }
};

// ─────────────────────────────────────────────────────────────────────────────
//  2. Car Rental Confirmation
// ─────────────────────────────────────────────────────────────────────────────

const sendRentalConfirmation = async (rental) => {
    if (!rental?.emailAddress) return;

    // Build promo rows if applicable
    let promoRows = '';
    if (rental.promoCode) {
        promoRows += row('Promo Code', `<code style="background:#1e2040;padding:2px 8px;border-radius:4px;color:#a5b4fc;">${rental.promoCode}</code>`);
    }
    if (rental.promoDiscount > 0) {
        promoRows += row('Promo Discount', `<span style="color:#4ade80;">-${formatPeso(rental.promoDiscount)}</span>`);
    }

    const finalTotal = rental.estimatedTotal - (rental.promoDiscount || 0);

    const content = `
      <!-- Greeting -->
      <h2 style="font-size: 22px; font-weight: 700; color: #f1f5f9; margin-bottom: 6px;">
        Rental Request Received! 🚙
      </h2>
      <p style="font-size: 14px; color: #94a3b8; margin-bottom: 4px;">
        Hi <strong style="color:#e2e8f0;">${rental.fullName}</strong>, thank you for your car rental request!
      </p>
      <p style="font-size: 14px; color: #94a3b8; margin-bottom: 24px;">
        Your rental application has been submitted and is <strong style="color:#fbbf24;">pending review</strong>.
        Our team will confirm your booking as soon as possible.
      </p>

      ${receiptBadge(rental.rentalId, 'Rental Reference ID')}

      <!-- Details Table -->
      <table class="details-table" width="100%" cellpadding="0" cellspacing="0"
        style="border-radius:10px; overflow:hidden; border:1px solid #2d2d3f; margin-bottom: 24px;">
        ${row('Status', statusBadge('Pending'))}
        ${row('Customer Name', rental.fullName)}
        ${row('Contact Number', rental.contactNumber)}
        ${row('Address', rental.address)}
        ${row('Vehicle', rental.vehicleName)}
        ${row('Price per Day', formatPeso(rental.pricePerDay))}
        ${row('Rental Start', formatDate(rental.rentalStartDate))}
        ${row('Return Date', formatDate(rental.returnDate))}
        ${row('Number of Days', `${rental.rentalDays} day${rental.rentalDays > 1 ? 's' : ''}`)}
        ${row('Destination', rental.destination)}
        ${rental.notes ? row('Notes', rental.notes) : ''}
        ${promoRows}
        ${row('Estimated Total', `<strong style="font-size:16px;color:#a5b4fc;">${formatPeso(finalTotal)}</strong>`)}
      </table>

      <!-- Requirements reminder -->
      <div style="background:#0d1a0d; border:1px solid #166534; border-radius:10px;
          padding:16px 20px; margin-bottom:20px;">
        <p style="font-size:13px; color:#4ade80; font-weight:700; margin-bottom:8px;">
          📋 Reminder — Required Documents at Pick-up:
        </p>
        <ul style="font-size:13px; color:#86efac; padding-left:18px; line-height:1.8;">
          <li>Valid Government-Issued ID (2 copies)</li>
          <li>Driver's License</li>
          <li>Proof of Billing / Address</li>
        </ul>
      </div>

      <p style="font-size: 13px; color: #64748b; line-height: 1.7; background:#13131c;
          border-left: 3px solid #6366f1; padding: 12px 16px; border-radius: 0 8px 8px 0;">
        ℹ️ Your rental is <strong style="color:#fbbf24;">pending</strong> — our staff will contact you to confirm
        availability and finalize the arrangement. Please keep your reference ID handy.
      </p>
    `;

    const html = wrapInShell(content,
        `Your rental request ${rental.rentalId} has been received. Thank you, ${rental.fullName}!`
    );

    try {
        await transporter.sendMail({
            from: process.env.EMAIL_FROM,
            to: rental.emailAddress,
            subject: `Rental Request Received — ${rental.rentalId} | Sandigan Car Rental`,
            html,
        });
        console.log(`✅ [Email] Rental confirmation sent to ${rental.emailAddress} (${rental.rentalId})`);
    } catch (err) {
        console.error(`❌ [Email] Failed to send rental confirmation to ${rental.emailAddress}:`, err.message);
        // Non-critical — do NOT re-throw
    }
};

// ─────────────────────────────────────────────────────────────────────────────

module.exports = { sendBookingConfirmation, sendRentalConfirmation };
